image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: rabbits.srht.site
sources:
    - https://git.sr.ht/~rabbits/uxn5
tasks:
    - package: |
        cd uxn5
        tar -czf ../out.tar.gz index.html src/
    - upload: 
        hut pages publish -d $site -s /uxn5  out.tar.gz
