image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/uxn5
sources:
    - https://git.sr.ht/~rabbits/uxn5
tasks:
    - package: |
        cd uxn5
        tar -czf out.tar.gz index.html src/
    - upload: 
        hub pages publish -d $site  out.tar.gz
